---
title: "Debbagh"
author: "El Ghali Debbagh"
format: html
editor: visual
execute: 
  warning: false
  error: false
  echo: false
---

#Question 2 https://github.com/ElGhaliDebbagh/galatic_systems

#Question 3

```{r}
#| message: false
here::i_am("ElGhaliDebbagh.Rproj")
library(here)
library(vroom)
library(dplyr)
library (stringr)
library(readr)
library(knitr)


```

```{r}
library(tidyr)
library(ggplot2)

```

```{r}


star_systems <- vroom(here("datasystems.csv"), )


num_star_systems <- nrow(star_systems)
num_variables <- ncol(star_systems)


valid_loading <- num_star_systems == 1048 && num_variables == 8

if (valid_loading) {
  cat("Data loaded successfully. Number of star systems:", num_star_systems, "\n")
} else {
  cat("Error loading data. Check the data file and loading process.\n")
}

numeric_variables <- sapply(star_systems, is.numeric)
if (all(numeric_variables)) {
  cat("All numerical variables are recognized.\n")
} else {
  cat("Not all variables are recognized as numerical.\n")
}

```

#Question 4

```{r}

missing_values <- colSums(is.na(star_systems))


num_obs_with_missing <- sum(apply(star_systems,1,anyNA))


data_summary <- data.frame(
  Metric=c("Number oobservations", "Number of variables", "Number of missin values", "Number of observations with at least one missing value"),
  Value=c(num_star_systems, num_variables, paste(missing_values, collapse=","),num_obs_with_missing)
)
kable(data_summary, format="markdown")

```


#Question 5
```{r}
ggplot(star_systems, aes(x = `STAR TEMPERATURE`, y = `relative luminosity`)) +
  geom_point() +
  labs(title = "Luminosity vs Temperature",
       x = "Temperature",
       y = "Relative Luminosity")
```

#Question 6
```{r}
extreme_stars <- data.frame(Variable=character(), Max_star=character(), Max_value=numeric(), Min_Star=character(), Min_Value=numeric())

numerical_variables<- names(star_systems)[sapply(star_systems, is.numeric)]
for (variable in numerical_variables) {
  max_index <-which.max(star_systems[[variable]])
  min_index<-which.min(star_systems[[variable]])
  
  extreme_stars<-rbind(extreme_stars,
                       data.frame(Variable=variable,
                                  Max_star=star_systems$STAR[max_index],
                                  Max_Value=star_systems[[variable]][max_index],
                                  Min_star=star_systems$STAR[min_index],
                                  Min_Value=star_systems[[variable]][min_index]))
  
}
kable(extreme_stars, format = "markdown", col.names = c("Variable", "Max Star", "Max value", "Min star", "Min value"))
```

#Question 7

#Question 8
```{r}
factions <-vroom(here("Factions.csv"))
sytem_faction<-vroom(here("SYTEM%FACTION.csv"))
```
#Question 9
```{r}
summary_table <- tibble(
  "Faction" = c("Abandoned", "Independent", "Undiscovered"),
  "Number of Star Systems" = c(
    sum(sytem_faction$FKEY %in% c("A", "I")),
    sum(sytem_faction$FKEY == "I"),
    sum(sytem_faction$FKEY == "U")
  )
)


kable(summary_table, format = "markdown")
```
#Question 10
```{r}
missing_systems <- anti_join(star_systems, sytem_faction, by = "Star_idx")
num_missing_systems <- nrow(missing_systems)
cat("number of star systems that cannot be found in the SYSTEM- CONTROL.csv file.
 :", num_missing_systems, "\n")

```

#Question 11
```{r}
merged_data <- merge(factions, sytem_faction, by ="FKEY")


at_least1_system_factions <- merged_data %>%
  group_by(`faction name`) %>%
  filter(any(!is.na(Star_idx)))


system_counts <- at_least1_system_factions %>%
  group_by(`faction name`) %>%
  summarise(Num_Systems = n())


ggplot(system_counts, aes(x = reorder(`faction name`, Num_Systems), y = Num_Systems)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Number of Star Systems Controlled by Each Faction",
       x = "Faction",
       y = "Number of Star Systems") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

